### ISSUE TITLE
having a hard time finding a good CL options parser

### ISSUE THREAD

**Issue by ORESoftware** [trentm/node-dashdash#19]
About to use this, because all other option parsing libs have problems.

One feature I do want, however, is ability to log out all options when the user uses --help option

is this available with this lib? Can't tell from the docs

**Comment by ORESoftware** [comment]
looks like this lib has it

help (String). Optional. Used for parser.help() output.

**Comment by trentm** [comment]
There is an example of usage in "examples/help.js":

```
$ node examples/help.js -h
usage: node help.js [OPTIONS]
options:
    -v, --verbose   More verbose output.
    -h, --help      Print this help and exit.
```

**Comment by ORESoftware** [comment]
cool thanks so far this is really rocking my world. nopt doesn't seem to do the --help option logging out of the box, and commander has some real problems as well as doing too much in having an interactive command line experience. this works for me.
