### ISSUE TITLE
confused about syntax for arrayOfBool, arrayOfString

### ISSUE THREAD

**Issue by ORESoftware** [trentm/node-dashdash#22]
Liking this lib, but I haven't figured out the correct command line syntax for passing an array as an option

say I have an arrayOfString, designated by this in the config:

```js
   {
        names: ['match'],
        type: 'arrayOfString',
        help: 'Use this to filter input to match the given JS regex'
    },
```

`$ node x  --match a b c`

a will be in the match array, but b and c will be parsed as args, not options, which of course makes sense

what is the correct syntax? I looked through the readme and couldn't find it :(

**Comment by ORESoftware** [comment]
Ok I think I figured it out, the correct way seems to be like so:

`$ node x --match a --match b --match c`

but I wonder if there is less verbose way to do it? Is there a better way?

thanks

**Comment by ORESoftware** [comment]
Perhaps a better way would be

--match [a,b,c]

And use some JS magic to evaluate it properly in the program from a string "[a,b,c]" to an array of strings ["a","b","c"]

**Comment by trentm** [comment]
Dashdash doesn't support a variable number of argv values to an option, nor more than a single value to an option.

Having a syntax using `[` would require the user to do quoting of the args to not have the shell interpret them. See https://github.com/trentm/node-dashdash/blob/master/examples/custom-option-arrayOfCommaSepString.js for an example that takes `-s a,b,c`.
