### ISSUE TITLE
How to allow secondary users to provide their own command line options

### ISSUE THREAD

**Issue by ORESoftware** [trentm/node-dashdash#24]
Say we have a command line app that takes 3 different options
```

var dashdash = require('dashdash');

var options = [
    {
        names: ['a'],
        type: 'bool',
        help: 'a is an option.'
    },
  {
        names: ['b'],
        type: 'bool',
        help: 'b is an option.'
    },

  {
        names: ['c'],
        type: 'bool',
        help: 'c is an option.'
    }
];

var opts = dashdash.parse({options: options});
```

so we can run the app with

`node index.js --a --b --c`

but if we did this

`node index.js --d `

we'd of course get an error saying the option was not recognized.

My only guess is that this might work?

`node index.js --a --b --c -- --d`

However, how can we allow users to provide their own options? I am writing a test library,
and I need users to be able to input their own options, along with options that are for the library, since my library calls their code -> we need options for both my library and their code.

Please advise, thanks!

**Comment by ORESoftware** [comment]
hi Trent - this is an important issue for me and looking forward to hearing back - just touching this thread so it don't get stale.

**Comment by trentm** [comment]
You could use the `allowUnknown: true` option to the parser. See https://github.com/trentm/node-dashdash#parser-config
