### ISSUE TITLE
Bash completion question

### ISSUE THREAD

**Issue by ORESoftware** [trentm/node-dashdash#34]
I was looking at this file:

https://github.com/trentm/node-dashdash/blob/master/examples/ddcompletion.js#L86

It says

  // Use the `parser.bashCompletion()` helper to create the Bash
  // completion file content, then just dump it.

Trying to follow what this means, but cannot figure it out

**Comment by trentm** [comment]
@ORESoftware That `if (opts.completion)` code path is implementing the `ddcompletion --completion` script option. I.e. it generates the bash completion code that a user needs to source in their Bash shell to get completion for the `ddcompletion` command. 

The way a script gets the Bash completion code is via the `parser.bashCompletion()` helper function provided by the dashdash module.

**Comment by ORESoftware** [comment]
ah ok, that's cooler than I thought, I thought I would have to generate the bash completion functions by hand.

**Comment by ORESoftware** [comment]
thanks Trent, I am really impressed by that bash completion code auto-generation, very useful, glad I didn't have to write that myself.

One question I have is:

```js
if(opts.completion){
  var code = dashdash.bashCompletionFromOptions({
    name: 'suman',
    options: options
  });
  console.log(code);
  return process.exit(0);
}
```

why would you ever use `dashdash.bashCompletion() `instead of `dashdash.bashCompletionFromOptions()`

I don't see a use for the former call.
