### ISSUE TITLE
Allow option combinations, example given

### ISSUE THREAD

**Issue by ORESoftware** [trentm/node-dashdash#47]
Say we are replicating some of the functionality of the find unix command:

```
dashfind  --match foo
dashfind -m foo  # shorthand for the above
```

this will match all files and directories that have 'foo' in their path.
But what if we only want to match files that have 'foo' but match all directories?

so that could be:

`dashfind --file-match  foo`

and then for dirs we could have:

`dashfind --dir-match  foo`

but what if there were option combinations, like so:

```
  {
    names: ['match', 'm'],
    type: 'arrayOfObject',
    help: 'Files must match at least one of these.',
    default: [] as Array<string>
  },
```

and that would be:

```js
[{
  "match": "foo",
  "file": true
},
{
  "match": "stew",
  "dir": true
},
{
  "dir": true,
  "file": true,
  "match":"bar"
}]
```

the above array might be given by:

`dashfind -mdf bar -fm foo -dm foo
`

**Comment by karfau** [comment]
You can easily add all three options as array of string and reduce them to the array you want after parsing.

This is such a specific use case that I don't think it makes sense for this lib to provide anything more then it already does.

**Comment by trentm** [comment]
I agree with @karfau, I don't want to add something like this.
