### ISSUE TITLE
Add option to include default values in the help output, similar to `includeEnv`

### ISSUE THREAD

**Issue by marshall007** [trentm/node-dashdash#9]
I find myself setting `default` and `helpArg` to the same value in most cases. It would be nice if `default` appeared as the placeholder in the help output by default unless explicitly overridden by `helpArg`.

**Comment by trentm** [comment]
@marshall007 Can you provide a real example or two? All my typical uses have different values for those. In my usage those fields have a separate meaning: `default` is the value that will be used if the opt isn't specified, `helpArg` is placeholder string giving a hint what type of option argument to provide.

**Comment by marshall007** [comment]
When the `helpArg` is not specified I think the `default` provides a good "hint" as you say. I guess really I'd just like for the defaults to be displayed in the help output and currently the best/only way to do that is by setting them as the `helpArg`.

Being able to specify some sort of template to override how the help text gets generated would also solve my problem.

**Comment by trentm** [comment]
Ah perhaps something like how env vars are included in help output if `includeEnv` is used (https://github.com/trentm/node-dashdash#help-config)?

**Comment by marshall007** [comment]
@trentm yea, that would be great! I'll update this issue to reflect that.

**Comment by trentm** [comment]
Will be in v1.10.0
